### ISSUE TITLE
No matching symbol 'SendAtCommand'

### ISSUE THREAD

**Issue by arnoutdekimo** [u-blox/m-center#1]
Undoubtably I am missing something, but I naively installed m-center, and attempted to execute a random script (ipApp_all_socketEchoTest_advance.atl), by executing it in m-center below:

![image](https://github.com/u-blox/m-center/assets/61543845/e4ecae5c-6ca5-4e2a-9c2e-740c9783c4a5)

This seems to fail in not understanding the function SendAtCommand.

Probably I am missing something, but I did not immediately find this back in the README.md, so posting it here

**Comment by rebatoma** [comment]
Hi.
What is the m-center SW version you are using? Latest available is 02.08.00: [https://www.u-blox.com/en/product/m-center](https://www.u-blox.com/en/product/m-center)

`SendAtCommand` is a function defined inside the common librayy of m-center.
In order to properly use inside the script, functions that are defined inside the common library, you need to select the "at_script" folder in the "Load AT script folder" icon as in the image below. 
![image](https://github.com/u-blox/m-center/assets/6113690/12e533f6-8ba5-4db2-84a0-5b071db3f852)
Then, from the "AT script" dropdown you can navigate inside the "internet_applications" folder and select the script you'd like to run.

Please refer to the README in [/m-center/tree/main/at_scripts/common_lib](https://github.com/u-blox/m-center/tree/main/at_scripts/common_lib) for further details. 

Let us know if the problem is solved or if further support is required. Thanks. Regards.

**Comment by arnoutdekimo** [comment]
Hi,

![image](https://github.com/u-blox/m-center/assets/61543845/aa715e8f-4e13-4ac3-9a83-057e5c1e0347)

As far as I can see, I am using the latest version then.

The issue was indeed that I selected a folder "too deep". Apparently, I should have taken indeed the at_scripts root directory, and that still allows to navigate inside subfolders, but it then also finds these common things.
